{% set name = "optimum-habana" %}
{% set version = "1.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/optimum-habana-{{ version }}.tar.gz
  sha256: bfe02df164de0250c0e75336d9bb1f92e674e9724e03750c94f0d1e508d64dc8

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - datasets
    - optimum
    - pillow
    - scipy
    - sentencepiece
    - tokenizers
    - pytorch
    - transformers >=4.20.0

test:
  imports:
    - optimum
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://huggingface.co/hardware/habana
  summary: |
    Optimum Habana is the interface between the Hugging Face Transformers library 
    and Habana Gaudi Processor (HPU). It provides a set of tools enabling easy model 
    loading and fine-tuning on single- and multi-HPU settings for different downstream tasks.
  license: Apache-2.0
  license_file:
    - LICENSE
  description: |
    Optimum Habana is the interface between the Hugging Face Transformers library 
    and Habana Gaudi Processor (HPU). It provides a set of tools enabling easy model 
    loading and fine-tuning on single- and multi-HPU settings for different downstream tasks.

    PyPI: [https://pypi.org/project/optimum-habana/](https://pypi.org/project/optimum-habana/)

  doc_url: https://huggingface.co/hardware/habana
  dev_url: https://github.com/huggingface/optimum-habana

extra:
  recipe-maintainers:
    - sugatoray
